### ISSUE TITLE
Occasional crash due to protocol error?

### ISSUE THREAD

**Issue by andypiper** [njh/mqtt-http-bridge#5]
Suspect this is either network or ruby-mqtt related

```
$  rackup
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:9292, CTRL+C to stop
127.0.0.1 - - [20/Jun/2013 16:46:33] "GET / HTTP/1.1" 200 12547 1.3553
127.0.0.1 - - [20/Jun/2013 16:46:35] "GET /favicon.ico HTTP/1.1" 404 25 1.2055
```

... after a short period

```
/Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/packet.rb:238:in `read_byte': MQTT::ProtocolException (MQTT::ProtocolException)
    from /Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/packet.rb:21:in `read'
    from /Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/client.rb:280:in `receive_packet'
    from /Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/client.rb:151:in `block (2 levels) in connect'
    from /Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/client.rb:151:in `loop'
    from /Users/andyp/Development/github/mqtt-http-bridge/.bundle/gems/ruby/1.9.1/gems/mqtt-0.0.9/lib/mqtt/client.rb:151:in `block in connect'
```

Seems to be non-deterministic and random. Seen both locally running on OS X, and also on cloud deployed bridge.

**Comment by njh** [comment]
Not seen this in a long time now

**Comment by andypiper** [comment]
ack, it is a long time since i tried this, fair to close.
